const appname = "eMart";
const credits = "@Kashif Shah";
const email = "Email";
const emailHint = "admin@gmail.com";
const password = "Password";
const passwordHint = "*******";
const forgetPassword = "Forget Password";
const login = "Login";
const singUp = "SignUp";
const createNewAccount = "or, create new account";
const loginWith = "Login With";
const name = "Name";
const retypePassword = "Retye Password";
const privacyPolicy = " Privacy Policy";
const termAndCondition = " Terms and Conditions";
const alreadHaveAccount = "Already have and account?";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const searchAnyThing = "Search anything...",
    todayDeal = "Today Deal",
    flashSale = "Flash Sale",
    topSalers = "Top Salers",
    brand = "Brand",
    topCategories = "Top Categories",
    featureCategories = "Feature Categories";
