// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5EQcapwJpFJsNuJi5-aXCZ8cN52fkMbE',
    appId: '1:707038241433:web:e24874f311328de70c8e08',
    messagingSenderId: '707038241433',
    projectId: 'e-commerce-app-81d34',
    authDomain: 'e-commerce-app-81d34.firebaseapp.com',
    storageBucket: 'e-commerce-app-81d34.appspot.com',
    measurementId: 'G-ZKP4WBRD89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEESZp2DLvAiDiy5CKFvcf38lRpGUHIPo',
    appId: '1:707038241433:android:04aff2fc86bad7530c8e08',
    messagingSenderId: '707038241433',
    projectId: 'e-commerce-app-81d34',
    storageBucket: 'e-commerce-app-81d34.appspot.com',
  );
}
